### ISSUE TITLE
Error when correct url or query is entered

### ISSUE THREAD

**Issue by PrajwalM2212** [HTTP-APIs/python-hydra-agent#74]
<img width="1463" alt="screen shot 2019-01-22 at 10 51 02 pm" src="https://user-images.githubusercontent.com/30733262/51554423-494c1d80-1e9b-11e9-81a1-716c6c22ca85.png">

Even when correct url is entered python hydra agent gives an error.

**Comment by ShravanDoda** [comment]
Error is also thrown when there's an extra '/' at the end of the URL because then it send a request to //vocab instead of /vocab. It'd be good if you could create a commit for checking the presence of '/' at the end of the URL. Moreover, return of `urlopen` hasn't been closed. It'd be good if you could add the `urlopen` function with context manager.

**Comment by Mec-iS** [comment]
`urllib` tools should be used to parse/unparse URLs

**Comment by xadahiya** [comment]
@ShravanDoda ^^
